base_url : http://www.pierrebaron.fr/pbckcode
dev : false
google_analytics_id: UA-21369110-4
site_url : http://www.pierrebaron.fr
navigation:
- text: Home
  url: /
- text: Blog
  url: /blog/
  layout: post
- text: Contact
  url: /contact/
subnavigation:
- text: Index
  url: /
- text: Examples
  url: /examples/
  dropdown :
    - text: Basic example
      url: basic/
    - text: Options example
      url: options/
    - text: Full example
      url: full/
    - text: Custom ACE Editor sources
      url: custom/
      label : 1.2.3
- text: Docs
  url: /docs/
sass:
  sass_dir: _sass
  style: :compressed